Fix when backing up to a new kipper database.

diff --git a/seqdb b/seqdb
--- a/seqdb
+++ b/seqdb
@@ -353,6 +353,11 @@ kipper_backup() {
         exit 1
     fi
  
+    # If the output database does not exist, create it.
+    if [[ ! -f "$2.md" ]]; then
+        kipper.py $2 -M fasta
+    fi
+
     foo="kipper.py $2 -l"
     fooIn=$($foo)
 
@@ -619,18 +624,6 @@ if [[ $(echo $?) -ne 0 ]]; then
     echo "mash cannot be called, check its installation, exiting"
     exit 1
 fi
-# phame
-phame -h > /dev/null
-if [[ $(echo $?) -ne 0 ]]; then
-    echo "phame cannot be called, check its installation, exiting"
-    exit 1
-fi
-# mashtree
-mashtree -h > /dev/null
-if [[ $(echo $?) -ne 0 ]]; then
-    echo "mashtree cannot be called, check its installation, exiting"
-    exit 1
-fi
 # picard
 picard -h > /dev/null
 if [[ $(echo $?) -ne 0 ]]; then
@@ -643,7 +636,18 @@ if [[ $(echo $?) -ne 0 ]]; then
     echo "kipper cannot be called, check its installation, exiting"
     exit 1
 fi
-
+# phame
+phame -h > /dev/null
+if [[ $(echo $?) -ne 0 ]]; then
+    echo "phame cannot be called, check its installation, exiting"
+    exit 1
+fi
+# mashtree
+mashtree -h > /dev/null
+if [[ $(echo $?) -ne 0 ]]; then
+    echo "mashtree cannot be called, check its installation, exiting"
+    exit 1
+fi
 
 # parse subcommands
 if [[ $1 == "build_db" ]]; then
